<?php
/* ===== Configuration for Slum CMS ===== */

/* Function-based configuration
================== */
$triggerclass = "slum"; //Class that makes elements editable by Slum

/* Uploads
================== */
$uploadpath = "img/"; //Path from webroot that images should be uploaded to - do not prepend a /. But do append.
$deleteoldupload = true; //Delete old file when new one is uploaded in its place

/* Text-area
================== */
$triggerplaintext = "plain"; //Keyword to set textarea to plaintext
$triggerwysiwyg = "wysiwyg"; //Keyword to set textarea to WYSIWYG (is default setting)
$defaulttextarea = $triggerwysiwyg; //Default textarea type - set to $triggerplaintext for plaintext textarea
$wysiwygbuttonconfig = "'bold','italic','underline','strikethrough','left','center','right','justify','ol','ul','fontSize','fontFormat','indent','outdent','xhtml'"; //Change which buttons appear on the wysiwyg editors (all available options can be found here: http://wiki.nicedit.com/w/page/515/Configuration%20Options)

/* Deletes
================== */
$triggerdeleteable = "deleteable"; //Trigger attribute for making an element deletable
$softdelete = false; //If softdelete is enabled, it simply sets the style of the element to hidden and removes the slum class; element exists but is not visible to the system nor to the user.

/* Templates
================== */
$triggertemplate = "slumtemplate"; //Trigger element for templates.
$triggervar = "slumvar"; //Trigger element for vars.

/* Generates
================== */
$generateddirname = "generated"; //Name of the directory in which generated files will be placed.
$generatedcssname = "slum.css"; //Name of the CSS-file generated by the system if templates are used.

/* Switches
================== */
$showpath = false; //Show path to the page underneath its name
$showversion = true; //Show version number on index page
$checkversion = true; //Check for new version of Slum CMS on login (only for root users).
$enabletemplates = true; //Controls template functionality and CSS generation.

//Less important configurations
$triggertitle = "slumtitle"; //Change the attributename for defining titles (e.g. slumtitle="First column", where slumtitle is triggertitle)
$triggertextarea = "textarea"; //Textarea defining attribute for HTML elements (e.g. textarea="plain", where textarea is the attribute)
$rootpath = $_SERVER['DOCUMENT_ROOT'] . "/"; //Makes all page URLS from webroot instead of relative to the Slum directory
$dbpages = "db/pages.json"; //Path to the database file containing information regarding pages
$dbusers = "db/users.php"; //Path to database file containing information regarding users
$dbconf = "db/conf.json"; //Path to system editable config file.
$version = "0.4"; //Version number of current release

/* Promotional-based configuration
================== */
$shortname = "Slum CMS";
?>
